export enum SubEmployerStatus {
  INVITED = "INVITED",
  ACTIVE = "ACTIVE",
  DISABLED = "DISABLED",
}

export const SUB_EMPLOYER_PERMISSIONS = {
  VIEW_APPLICANTS: "VIEW_APPLICANTS",
  VIEW_JOBS: "VIEW_JOBS",
  CHAT_WITH_APPLICANTS: "CHAT_WITH_APPLICANTS",
  SEND_ASSIGNMENTS: "SEND_ASSIGNMENTS",
  VIEW_INTERVIEWS: "VIEW_INTERVIEWS",
  SCHEDULE_INTERVIEWS: "SCHEDULE_INTERVIEWS",
  DOWNLOAD_RESUMES: "DOWNLOAD_RESUMES",
  CHANGE_APPLICATION_STATUS: "CHANGE_APPLICATION_STATUS",
} as const;
